### ISSUE TITLE
'RecognitionOptions' object has no attribute 'ca'

### ISSUE THREAD

**Issue by Petilia** [salute-developers/salute-speech#2]
При использовании питоновского API возникает следующая ошибка:

Traceback (most recent call last):
  File "recognize.py", line 162, in <module>
    main()
  File "recognize.py", line 158, in main
    recognize(parser.parse_args(namespace=Arguments()))
  File "/usr/lib/python3.6/argparse.py", line 1743, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.6/argparse.py", line 1766, in parse_known_args
    setattr(namespace, action.dest, action.default)
  File "recognize.py", line 110, in __setattr__
    self._set_option(self.recognition_options, key, value)
  File "recognize.py", line 119, in _set_option
    setattr(obj, key, value)
AttributeError: 'RecognitionOptions' object has no attribute 'ca'

Запускаю распознавание кодом, представленным в ReadMe:
python3 recognize.py [--ca /path/to/russian_trusted_root_ca] --token "<access_token>" --file "<file>"

С чем может быть связана эта проблема?

**Comment by simakazi** [comment]
Проблема исправлена в новой версии клиентского кода - обновите, пожалуйста, recognize.py.
